# Generated by Django 2.2.17 on 2021-01-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('direccion', models.CharField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('plano', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='abmapp.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('tipoArea', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=2, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=20)),
                ('radioMayor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('radioMenor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usuarioAlta', models.CharField(max_length=500)),
                ('usuarioBaja', models.CharField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='abmapp.piso')),
            ],
        ),
    ]
