# Generated by Django 2.2.17 on 2021-01-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='usuarioBaja',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
