# Generated by Django 2.2.17 on 2020-12-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clickleable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArea', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=2, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=20)),
                ('radioMayor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('radioMenor', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
