# Generated by Django 2.2.17 on 2020-12-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Click', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickleable',
            name='idSite',
            field=models.IntegerField(default=1),
        ),
    ]
