# Generated by Django 2.2.17 on 2020-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Click', '0002_clickleable_idsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickleable',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
